project:
  type: website
  output-dir: docs
  title: "Formulacion y Evaluacion de Proyectos de Inversion"

# _quarto.yml
website:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: lessons/index.qmd
        text: "Lecciones"


format:
  html:
    theme: dark

lang: es

